flaskblog/main/routes.py
from flask import Blueprint, request, render_template,g, current_app, url_for, redirect
from  flaskblog.models import Post, Upvote_association
from flask_login import current_user, login_required
from flaskblog.main.forms import SearchForm
from flask_babel import get_locale
import requests
import json
from json import Response
from datetime import datetime
from flaskblog.scrape import scrape_medium
from flaskblog import db
from sqlalchemy import func
from flask_paginate import Pagination, get_page_parameter
main = Blueprint('main',__name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).all()
    top_rated_posts.reverse()
    
    recommended_posts=[]
    if current_user.is_authenticated:
        for post in top_rated_posts:
            if current_user.is_following_domain(post.domain):
                recommended_posts.append(post)
        pagination = Pagination(page=page, total=len(recommended_posts), search=False, record_name='recommended_posts')
        return render_template('home.html',pagination=pagination, latest_posts=latest_posts, current_user=current_user, top_rated_posts = top_rated_posts, recommended_posts=recommended_posts)
    else:
        recommended_posts=Post.query.order_by(Post.date_posted.desc()).all()
        pagination = Pagination(page=page, total=len(recommended_posts), search=False, record_name='recommended_posts')
        return render_template('home.html',pagination=pagination, latest_posts=latest_posts, current_user=current_user, top_rated_posts = top_rated_posts, recommended_posts=recommended_posts)
@main.route("/about")
def about():
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    return render_template('about.html', title = 'About', top_rated_posts=top_rated_posts, latest_posts=latest_posts)


@main.before_app_request
def before_request():
    if current_user.is_authenticated:
        g.search_form = SearchForm()
    g.locale = str(get_locale())

@main.route('/search')
@login_required
def search():
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    if not g.search_form.validate():
        return redirect(url_for('main.home'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])
    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None

    query_string = g.search_form.q.data
    url= 'https://api.stackexchange.com/2.2/search/advanced?page=1&pagesize=20&order=desc&sort=relevance&site=stackoverflow'    
    payload ={ 'q':query_string , 'accepted':'true', 'closed':'true', 'migrated':'false',}
    stack_response = json.loads(requests.get(url, params=payload).text)
    medium_response = scrape_medium(query_string)
    return render_template('search.html', title='Search', posts=posts,
                           next_url=next_url, prev_url=prev_url, stack_response=stack_response['items'], medium_response=medium_response, top_rated_posts=top_rated_posts, latest_posts=latest_posts)


@main.route("/toggle_tour_view", methods=['POST'])
def toggle_tour_view():
    current_user.can_view_tour=False
    db.session.commit()
    print(current_user.can_view_tour)
    status_code = Response(status=200)
    return status_code

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, Response, jsonify, json)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Comment, Downvote_association, Upvote_association, Domain
from flaskblog.posts.forms import PostForm, CommentForm, UpvoteForm, DownvoteForm
from flaskblog.domains.forms import DomainForm
from flaskblog.domains.routes import get_domains
from sqlalchemy import func
posts = Blueprint('posts',__name__)




@posts.route("/post/new", methods = ['GET','POST'])
@login_required
def new_post():
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    form = PostForm()
    domain_form =DomainForm()
    lst = get_domains()
    d=[]
    for x in lst:
        d.append((x,x))
    form.domain.choices=d
    if form.validate_on_submit():
        domain_name=dict(form.domain.choices).get(form.domain.data)
        domain=Domain.query.filter_by(domain_name=domain_name).first_or_404()
        post=Post(title=form.title.data, content = form.content.data, author=current_user,domain_id=domain.id)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post', form = form, legend = 'New Post', domain_form=domain_form, top_rated_posts=top_rated_posts, latest_posts=latest_posts)

@posts.route("/post/<int:post_id>", methods = ['GET', 'POST'])
@login_required
def post(post_id):
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post=post)
    print('Hey')
    for posts in top_rated_posts:
        print(posts)
    form = CommentForm()
    if form.validate_on_submit():
        comment=Comment(content=form.content.data, author=current_user, post=post)
        db.session.add(comment)
        db.session.commit()
        return Response(status=200)
    return render_template('post.html',title=post.title,post=post, form= form, comments=comments, top_rated_posts=top_rated_posts, latest_posts=latest_posts)

@posts.route("/post/<int:post_id>/add_comment", methods = ['POST'])
def comment(post_id):
    post=Post.query.get_or_404(post_id)
    form=CommentForm(request.form)
    if form.validate_on_submit():
        comment=Comment(content=form.content.data, author=current_user, post=post)
        db.session.add(comment)
        db.session.commit()
        return Response(status=200)
    return Response(status=500)

@posts.route("/post/<int:post_id>/update", methods = ['GET','POST'])
def update_post(post_id):
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    post = Post.query.get_or_404(post_id)
    if(post.author != current_user):
        abort(403)
    form = PostForm()
    domain_form = DomainForm()
    lst = get_domains()
    d=[]
    for x in lst:
        d.append((x,x))
    form.domain.choices=d
    if form.validate_on_submit():
        domain_name=dict(form.domain.choices).get(form.domain.data)
        domain=Domain.query.filter_by(domain_name=domain_name).first_or_404()
        post.title = form.title.data
        post.content = form.content.data
        post.domain=domain
        db.session.commit()
        flash('Post has been updated','success')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method == 'GET':
        form.title.data=post.title
        form.content.data=post.content
        form.submit.data='Update'
    return render_template('create_post.html',title='Update post', form = form, legend = 'Update Post', domain_form=domain_form, top_rated_posts=top_rated_posts, latest_posts=latest_posts)

@posts.route('/posts/<int:post_id>/is_upvoted')
@login_required
def is_upvoted(post_id):
    x=Upvote_association.query.get((current_user.id, post_id))
    if x != None:
        return jsonify({'text':'Upvoted'})
    else:
        return jsonify({'text':'Upvote'})
    
@posts.route('/posts/<int:post_id>/is_downvoted')
@login_required
def is_downvoted(post_id):
    x=Downvote_association.query.get((current_user.id, post_id))
    if x != None:
        return jsonify({'text':'Downvoted'})
    else:
        return jsonify({'text':'Downvote'})

@posts.route("/post/<int:post_id>/delete", methods = ['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if(post.author != current_user):
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'success')
    return redirect(url_for('main.home'))

@posts.route('/post/<int:post_id>/upvote', methods=['POST'])
def upvote(post_id):
    x=Upvote_association.query.get((current_user.id, post_id))
    y=Downvote_association.query.get((current_user.id, post_id))

    a=Upvote_association()
    a.post=Post.query.get_or_404(post_id)
    a.user=current_user
    if y != None:
        db.session.delete(y)
    current_user.children_upvoted_posts.append(a)
    db.session.commit()
    status_code = Response(status=200)
    return status_code 

@posts.route('/post/<int:post_id>/remove_upvote', methods=['POST'])
def remove_upvote(post_id):
    x=Upvote_association.query.get((current_user.id, post_id))
    db.session.delete(x)
    db.session.commit()
    status_code = Response(status=200)
    return status_code 


@posts.route('/post/<int:post_id>/downvote',methods=['POST'])
def downvote(post_id):
    x=Upvote_association.query.get((current_user.id, post_id))
    y=Downvote_association.query.get((current_user.id, post_id))
    a=Downvote_association()
    a.post=Post.query.get_or_404(post_id)
    a.user=current_user
    if x != None:
        db.session.delete(x)
    current_user.children_downvoted_posts.append(a)
    db.session.commit()
    status_code = Response(status=200)
    return status_code 

@posts.route('/post/<int:post_id>/remove_downvote', methods=['POST'])
def remove_downvote(post_id):
    y=Downvote_association.query.get((current_user.id, post_id))
    db.session.delete(y)
    db.session.commit()
    status_code = Response(status=200)
    return status_code 

flaskblog/users/routes.py
from flask import  current_app, render_template, url_for, flash, redirect, request, abort
from flaskblog.users.forms import Follow, ResetPasswordForm, RequestResetForm,RegistrationForm, LogIn, UpdateAccountForm
from flaskblog.models  import User, Post,followers, Upvote_association
from flaskblog import  db, bcrypt, mail
from flask_login import login_user, current_user, logout_user, login_required
import secrets, os
from PIL import Image
from datetime import datetime
from flask_mail import Message
from flaskblog.users.utils import send_reset_email, save_picture
from sqlalchemy import func


from flask import Blueprint
users = Blueprint('users',__name__)
latest_posts=[]
top_rated_posts=[]



@users.route("/register", methods=[ 'GET','POST'])
def register():
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password = hashed_password, email = form.email.data)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        next_page = request.args.get('next')
        return redirect(next_page) if next_page else redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form = form, top_rated_posts=top_rated_posts, latest_posts=latest_posts)

@users.route("/login", methods = ['GET', 'POST'])
def login():
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LogIn()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form, top_rated_posts=top_rated_posts, latest_posts=latest_posts)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET','POST'])
@login_required
def account():
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file=picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data=current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename ="profile_pics/"+current_user.image_file)
    return render_template('account.html', title='Account', image_file= image_file, form = form, top_rated_posts=top_rated_posts, latest_posts=latest_posts)

@users.route("/reset_password",methods=['GET','POST'])
def reset_request():
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user= User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to your registered email id for resetting your password')
    return render_template('reset_request.html', title='Reset Password', form=form, top_rated_posts=top_rated_posts, latest_posts=latest_posts)

@users.route("/reset_password/<token>",methods=['GET','POST'])
def reset_token(token):
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is invalid or expired token','warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()    
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_password
        db.session.commit()
        flash('Password successfully changed', 'success')
        next_page = request.args.get('next')
        return redirect(next_page) if next_page else redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form =form, top_rated_posts=top_rated_posts, latest_posts=latest_posts )

@users.route("/user/<string:username>")
@login_required
def user_profile(username):
    latest_posts=Post.query.order_by(Post.date_posted.desc()).limit(6).all()
    top_rated_posts=Post.query.outerjoin(Upvote_association).group_by(Post.id).order_by(func.count().desc()).limit(6).all()
    follow_form = Follow()

    page=request.args.get('page',1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        follow_form.follow_button.label.text='Followed'

    posts=Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page,per_page=5)
    return render_template('user_profile.html',posts = posts, user=user, current_user=current_user, follow_form=follow_form, top_rated_posts=top_rated_posts, latest_posts=latest_posts)

@users.route("/user/<int:user_id>/follow", methods=['POST'])
def follow(user_id):
    user=User.query.get_or_404(user_id)
    if request.args.get('str') == 'Follow':
        current_user.follow(user)
    else:
        current_user.unfollow(user)
    return redirect(url_for('users.user_profile', username=user.username))

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in recommended_posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}">
            <div class="media-body">
              <div class = "article-metadata">
                  <a class="mr-2" href="{{ url_for('users.user_profile', username=post.author.username) }}">{{ post.author.username }}</a>
                  <a class="mr-2" href="{{ url_for('domains.domain_profile', domain_name=post.domain.domain_name) }}">{{ post.domain.domain_name }}</a>
                  <small class="text-muted">{{ post.date_posted.strftime('%y-%m-%d') }}</small>
              </div>
              <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
              <div class="article-metadata"></div>
              <div class="home-content article-content">
                <p>{{ post.content | safe }}</p>
              </div>
              <div><a href="{{ url_for('posts.post', post_id=post.id) }}">Read more...</a></div>
              <div class="article-metadata"></div>
              {% if current_user.is_authenticated %}
                <div>
                  <p>
                    <span id="upvote"><span class="vote" style="cursor:unset;"></span> <span id ="upvote_count">{{ post.upvoters|length }}</span> </span>
                    <span id="downvote"><span class="votd " style="cursor:unset;"></span> <span id ="downvote_count">{{ post.downvoters|length }}</span></span>
                    &nbsp;<span id="comment"> <span><i class="far fa-comment"></i></span>  <span id ="comment|count">{{ post.comments|length }}</span></span>
                  </p>
                </div>
              {% endif %}  
            </div>
        </article>
    {% endfor %}
    {{ pagination.links }}
    <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>   
    
{% endblock content %}


{% block Optional_js %}
    {% if current_user.is_authenticated and current_user.can_view_tour %}

        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

        <script type="text/javascript">
          const driver = new Driver({opacity: .8,
                                    stageBackground: '#5f788a',});


          driver.defineSteps([
            {
              element: '#tour-start-item-1',
              popover: {
                className: 'first-step-popover-class',
                title: 'Title on Popover',
                description: 'Body of the popover',
                position: 'bottom'
              }
            },
            {
              element: '#tour-item-2',
              popover: {
                title: 'Title on Popover',
                description: 'Body of the popover',
                position: 'bottom'
              }
            },
            {
              element: '#tour-item-3',
              popover: {
                title: 'Title on Popover',
                description: 'Body of the popover',
                position: 'bottom'
              }
            },
            {
              element: '#tour-item-4',
              popover: {
                title: 'Title on Popover',
                description: 'Body of the popover',
                position: 'bottom'
              }
            },
            {
              element: '#tour-item-5',
              popover: {
                title: 'Title on Popover',
                description: 'Body of the popover',
                position: 'bottom'
              }
            },
            {
              element: '#tour-item-6',
              popover: {
                title: 'Title on Popover',
                description: 'Body of the popover',
                position: 'bottom'
              }
            },
            {
              element: '#tour-item-7',
              popover: {
                title: 'Title on Popover',
                description: 'Body of the popover',
                position: 'right'
              }
            },
            {
              element: '#tour-item-8',
              popover: {
                title: 'Title on Popover',
                description: 'Body of the popover',
                position: 'left'
              }
            },
          ]);
          
          driver.start();
        
          $(document).ready(function(){
            $.ajax({
              url:" {{ url_for('main.toggle_tour_view') }} ",
              type:"POST",
              success:function(response){
              }
            });
          });
      </script>
    {% endif %}
{% endblock Optional_js %}
 

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}">
        <div class="media-body">
            <div class = "article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_profile', username=post.author.username) }}">{{ post.author.username }}</a>
                <a class="mr-2" href="{{ url_for('domains.domain_profile', domain_name=post.domain.domain_name) }}">{{ post.domain.domain_name }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%y-%m-%d') }}</small>

                {% if post.author == current_user %}
                  <span class="dropdown" style="float: right; cursor: pointer;">
                    <i class="fas fa-ellipsis-v" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                      <a class="dropdown-item" href="#" data-toggle="modal" data-target="#deleteModal">Delete</a>
                    </div>
                  </span>
                {% endif %} 
            </div>
            <h2 class="article-title">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content | safe }}</p>
            {% if current_user.is_authenticated %}
              <div>
                <p>
                  <span id="upvote"><span class="vote"></span> <span id ="upvote_count">{{ post.upvoters|length }}</span> </span>
                  <span id="downvote"><span class="votd"></span> <span id ="downvote_count">{{ post.downvoters|length }}</span></span>
                </p>
              </div>
            {% endif %}
        </div>
    </article>
    
    <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
  <!--Comments section -->
  <div id="comments_section">
    <p> Comments</p>
    {% for comment in post.comments %}
      <div class="card">
        <div class="card-header">
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p>{{ comment.content }}</p>
            <footer class="blockquote-footer"><img src="{{ url_for('static', filename='profile_pics/'+comment.author.image_file) }}" class="rounded-circle comment-img" >{{ comment.author.username }} said at <cite title="Source Title">{{ comment.date_posted}}</cite></footer>
          </blockquote>
        </div>
      </div>
    {% endfor %}
  </div>
  <!--Write a comment-->
  {% if current_user.is_authenticated %}
    <div class="card">
      <div class="card-header">
        
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <img src="{{ url_for('static', filename='profile_pics/'+current_user.image_file) }}" class="rounded-circle comment-img" >
          <form id="comment" method="POST", action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                  {{ form.content(class="form-control form-control-lg", placeholder = "Write a comment ") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>
          </form>
        </blockquote>
      </div>
    </div>
  {% endif %}
  <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script>
    
    $('#comment').on('submit', function(e){
      e.preventDefault();
      $.ajax({
        url:" {{ url_for('posts.comment', post_id=post.id) }} ",
        data: $('#comment').serialize(),
        type:"POST",
        success:function(response){
          $("#comments_section").load("{{ url_for('posts.post', post_id=post.id)}}"+" #comments_section")
        }
      });
    });

    $(document).ready(function(){
      $.ajax({
        url:"{{ url_for('posts.is_upvoted', post_id=post.id) }}",
        type: "GET",
        success:function(response){
          if(response.text=="Upvoted")
          {
            $(".vote").toggleClass("on");
          }
        }
      });
      $.ajax({
        url:"{{ url_for('posts.is_downvoted', post_id=post.id) }}",
        type: "GET",
        success:function(response){
          if(response.text=="Downvoted")
          {
            $(".votd").toggleClass("on");
          }
        }
      });
    });
    
    function is_upvoted(){
      let x=$.ajax({
        url:"{{ url_for('posts.is_upvoted', post_id=post.id) }}",
        type: "GET",
        async:false,
        success:function(response){
          return response;
        }
      }).responseJSON;
      if(x.text==="Upvoted")
        return true;
      else
        return false;
    }

    function is_downvoted(){
      let x=$.ajax({
        url:"{{ url_for('posts.is_downvoted', post_id=post.id) }}",
        type: "GET",
        async:false,
        success:function(response){
          return response;
        }
      }).responseJSON;
      if(x.text==="Downvoted")
        return true;
      else
        return false;
    }
    
    $("#upvote").on('click',function(){
      event.preventDefault();
      if(is_upvoted() ==  false)
      {
        if(is_downvoted()==true)
          $(".votd").toggleClass("on");
        console.log("1");  
        $.ajax({
          url:" {{ url_for('posts.upvote', post_id=post.id) }}",
          type: "POST",
          success: function(response){
            $(".vote").toggleClass("on");
            $("#upvote_count").load("{{ url_for('posts.post', post_id=post.id)}}"+" #upvote_count")
            $("#downvote_count").load("{{ url_for('posts.post', post_id=post.id)}}"+" #downvote_count")
          }
        });
      }
      else
      {
        $.ajax({
          url:" {{ url_for('posts.remove_upvote', post_id=post.id) }}",
          type: "POST",
          success: function(response){
            $(".vote").toggleClass("on");
            $("#upvote_count").load("{{ url_for('posts.post', post_id=post.id)}}"+" #upvote_count")
            $("#downvote_count").load("{{ url_for('posts.post', post_id=post.id)}}"+" #downvote_count")
          }
        });
      }
    });


    $("#downvote").on('click',function(){
      event.preventDefault();
      if(is_downvoted()==false)
      {  
        if(is_upvoted()==true)
        {
          $(".vote").toggleClass("on");
        }
        $.ajax({
          url:" {{ url_for('posts.downvote', post_id=post.id) }}",
          type: "POST",
          success: function(response){
            $(".votd").toggleClass("on");
            $("#downvote_count").load("{{ url_for('posts.post', post_id=post.id)}}"+" #downvote_count")
            $("#upvote_count").load("{{ url_for('posts.post', post_id=post.id)}}"+" #upvote_count")
          }
        });
      }
      else
      {
        $.ajax({
          url:" {{ url_for('posts.remove_downvote', post_id=post.id) }}",
          type: "POST",
          success: function(response){
            $(".votd").toggleClass("on");
            $("#downvote_count").load("{{ url_for('posts.post', post_id=post.id)}}"+" #downvote_count")
            $("#upvote_count").load("{{ url_for('posts.post', post_id=post.id)}}"+" #upvote_count")
          }
        });
      }
    });
  </script>
{% endblock content %}